update Dockerfile and ci-cd

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -9,6 +9,10 @@ on:
 #### Global environment variable ####
 env:
   NODE_VERSION: 22
+  IMAGE_NAME: react-app
+  CONTAINER_NAME: react-container
+  REGISTRY: ghcr.io
+  IMAGE_TAG: latest
 
 jobs:
   build:
@@ -94,6 +98,44 @@ jobs:
             echo "Failed to build the React app." >&2
             exit 1
           fi
+
+      - name: Ensure Docker is installed
+        run: |
+          if ! command -v docker &> /dev/null
+          then
+            echo "Docker not found — installing now..."
+            sudo apt-get update
+            sudo apt-get install -y ca-certificates curl gnupg lsb-release
+            sudo mkdir -p /etc/apt/keyrings
+            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
+            echo \
+              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
+              https://download.docker.com/linux/ubuntu \
+              $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+            sudo apt-get update
+            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
+          else
+            echo "Docker is already installed!"
+            docker --version
+          fi
+
+      - name: Verify Docker Installation
+        run: docker --version
+
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Build Docker image
+        run: docker build -t ${{ env.IMAGE_NAME }} .
+
+      - name: Tag image
+        run: docker tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
+
+      - name: Push image to Docker Hub
+        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
 
       #### 6. Upload build artifact to GitHub ####
       - name: Upload production build artifact
